wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.11
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    m:
    - 1: trainer/global_step
      6:
      - 3
    python_version: 3.10.2
    start_time: 1687445230
    t:
      1:
      - 1
      - 9
      - 41
      3:
      - 7
      - 13
      - 15
      - 23
      4: 3.10.2
      5: 0.12.11
      8:
      - 5
cfg/accelerator:
  desc: null
  value: None
cfg/accumulate_grad_batches:
  desc: null
  value: None
cfg/amp_backend:
  desc: null
  value: native
cfg/amp_level:
  desc: null
  value: None
cfg/auto_lr_find:
  desc: null
  value: false
cfg/auto_scale_batch_size:
  desc: null
  value: false
cfg/auto_select_gpus:
  desc: null
  value: false
cfg/batch_size:
  desc: null
  value: 128
cfg/benchmark:
  desc: null
  value: None
cfg/check_val_every_n_epoch:
  desc: null
  value: 1
cfg/checkpoint_callback:
  desc: null
  value: None
cfg/data_dir:
  desc: null
  value: /home/wolfda/Data/PreTrain_Lung/Data/Hash_Vol_12_LIDC
cfg/dataset:
  desc: null
  value: medical
cfg/default_root_dir:
  desc: null
  value: None
cfg/detect_anomaly:
  desc: null
  value: false
cfg/deterministic:
  desc: null
  value: false
cfg/devices:
  desc: null
  value: None
cfg/enable_checkpointing:
  desc: null
  value: true
cfg/enable_model_summary:
  desc: null
  value: true
cfg/enable_progress_bar:
  desc: null
  value: true
cfg/fast_dev_run:
  desc: null
  value: false
cfg/flush_logs_every_n_steps:
  desc: null
  value: None
cfg/gpus:
  desc: null
  value: 1
cfg/gradient_clip_algorithm:
  desc: null
  value: None
cfg/gradient_clip_val:
  desc: null
  value: None
cfg/group:
  desc: null
  value: BYOL
cfg/ipus:
  desc: null
  value: None
cfg/job_type:
  desc: null
  value: Pre-training
cfg/learning_rate:
  desc: null
  value: 0.001
cfg/limit_predict_batches:
  desc: null
  value: None
cfg/limit_test_batches:
  desc: null
  value: None
cfg/limit_train_batches:
  desc: null
  value: None
cfg/limit_val_batches:
  desc: null
  value: None
cfg/log_every_n_steps:
  desc: null
  value: 50
cfg/log_gpu_memory:
  desc: null
  value: None
cfg/logger:
  desc: null
  value: true
cfg/max_epochs:
  desc: null
  value: None
cfg/max_steps:
  desc: null
  value: -1
cfg/max_time:
  desc: null
  value: None
cfg/meta_dir:
  desc: null
  value: .
cfg/min_epochs:
  desc: null
  value: None
cfg/min_steps:
  desc: null
  value: None
cfg/move_metrics_to_cpu:
  desc: null
  value: false
cfg/multiple_trainloader_mode:
  desc: null
  value: max_size_cycle
cfg/name:
  desc: null
  value: Test
cfg/num_classes:
  desc: null
  value: 1
cfg/num_nodes:
  desc: null
  value: 1
cfg/num_processes:
  desc: null
  value: None
cfg/num_sanity_val_steps:
  desc: null
  value: 2
cfg/num_workers:
  desc: null
  value: 8
cfg/offline:
  desc: null
  value: false
cfg/online_ft:
  desc: null
  value: false
cfg/overfit_batches:
  desc: null
  value: 0.0
cfg/plugins:
  desc: null
  value: None
cfg/precision:
  desc: null
  value: 32
cfg/prepare_data_per_node:
  desc: null
  value: None
cfg/process_position:
  desc: null
  value: 0
cfg/profiler:
  desc: null
  value: None
cfg/progress_bar_refresh_rate:
  desc: null
  value: None
cfg/reload_dataloaders_every_n_epochs:
  desc: null
  value: 0
cfg/replace_sampler_ddp:
  desc: null
  value: true
cfg/resume_from_checkpoint:
  desc: null
  value: None
cfg/savepath:
  desc: null
  value: /home/wolfda/Data/Spark/PreTrain/BYOL
cfg/stochastic_weight_avg:
  desc: null
  value: false
cfg/strategy:
  desc: null
  value: None
cfg/sync_batchnorm:
  desc: null
  value: false
cfg/tags:
  desc: null
  value:
  - BYOL
cfg/terminate_on_nan:
  desc: null
  value: None
cfg/tpu_cores:
  desc: null
  value: None
cfg/track_grad_norm:
  desc: null
  value: -1
cfg/val_check_interval:
  desc: null
  value: None
cfg/warmup_epochs:
  desc: null
  value: 10
cfg/weight_decay:
  desc: null
  value: 1.5e-06
cfg/weights_save_path:
  desc: null
  value: None
cfg/weights_summary:
  desc: null
  value: top
model/params/non_trainable:
  desc: null
  value: 0
model/params/total:
  desc: null
  value: 70118528
model/params/trainable:
  desc: null
  value: 70118528
tags:
  desc: null
  value:
  - BYOL
